name = "DensityRatioEstimation"
uuid = "ab46fb84-d57c-11e9-2f65-6f72e4a7229f"
authors = ["Kai Xu <xukai921110@gmail.com>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.0"
Requires = "0.5.2"
Parameters = "0.12.0"

[extras]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distances", "Distributions", "JuMP", "Ipopt"]
